---
- name: install supervisor
  apt: pkg=supervisor state=present

- name: configure supervisor open file limit
  lineinfile: dest=/etc/default/supervisor line='ulimit -n 51200' state=present
  notify:
    - restart supervisor
