---
- name: install nfs-common
  apt:
    name: nfs-common
    state: present

- name: make mount point
  file: path={{ item.name }} state=directory owner=daemon group=daemon mode=0755
  with_items: "{{ nfs_client_mount }}"

- name: mount
  mount:
    name: "{{ item.name }}"
    src: "{{ item.src }}"
    opts: "{{ item.opts }}"
    fstype: nfs
    state: mounted
  with_items: "{{ nfs_client_mount }}"
