---
- hosts: all
  become: true

  roles:
    - server-setup/apt-tune
    - server-setup/disable-ipv6
    - server-setup/uninstall-aegis
    - server-setup/dns
    - server-setup/hosts
    - server-setup/common
    - server-setup/timezone
    - server-setup/locale
    - server-setup/ntp
    - server-setup/sysctl
    - server-setup/vnstat
