---
- name: add python ppa
  apt_repository: repo='ppa:deadsnakes/ppa' state=present update_cache=yes
  when: ansible_distribution_version <= "16.04"

- name: install python3.8 related packages
  apt:
    state: present
    pkg:
      - python3.8
      - python3.8-dev
      - python3.8-venv

- name: install python dev related packages
  apt:
    state: present
    pkg:
      - zlib1g-dev
      - libjpeg-dev
      - libfreetype6-dev
      - libpng-dev
      - libffi-dev
      - libssl-dev
      - libreadline-dev
      - libevent-dev
      - libpq-dev
      - libmysqlclient-dev
      - libsqlite3-dev
      - libyaml-dev
      - libxml2-dev
      - libxslt1-dev
      - libcurl4-openssl-dev
      - libncurses5-dev
      - libldap2-dev
      - libsasl2-dev
      - virtualenv
