---
- name: remove old haproxy ppa
  apt_repository: repo='ppa:vbernat/haproxy-1.8' state=absent

- name: add haproxy ppa
  apt_repository: repo='ppa:vbernat/haproxy-2.0' state=present update_cache=yes

- name: install haproxy
  apt:
    pkg: haproxy
    state: present

- name: ensure haproxy is started and enabled
  service:
    name: haproxy
    state: started
    enabled: yes
