---
- name: install old version kernel
  apt: pkg='{{ item }}' state=present update_cache=yes cache_valid_time=86400
  with_items:
    - linux-image-{{kernel_pin_version}}

- name: remove kernel meta package
  apt: pkg='{{ item }}' state=absent
  with_items:
    - linux-image-amd64

- name: remove unwanted kernels
  shell: apt-get -y purge $(dpkg -l|egrep '^ii  linux-(im|he)'|awk '{print $2}'|grep -v {{ kernel_pin_version }})
  args:
    warn: no
  register: remove_result
  changed_when: "'The following packages will be REMOVED' in remove_result.stdout"
