---
- name: Check for reboot hint.
  shell: if [ $(readlink -f /vmlinuz) != /boot/vmlinuz-$(uname -r) ]; then echo 'reboot'; else echo 'no'; fi
  register: reboot_hint
  failed_when: False
  changed_when: False

- name: Rebooting vagrant...
  command: 'vagrant reload'
  delegate_to: 127.0.0.1
  become: no
  when: reboot_hint.stdout.find("reboot") != -1
  register: rebooting

- name: Wait for reboot...
  pause: seconds=1
  when: rebooting|changed
