---
- name: install ntp
  apt:
    pkg: ntp
    state: present
    update_cache: yes
    cache_valid_time: 86400

- name: configure ntp
  template:
    src: ntp.conf.j2
    dest: /etc/ntp.conf
  notify: restart ntp

- meta: flush_handlers

- name: ensure ntp is started and enabled
  service:
    name: ntp
    state: started
    enabled: yes
